CREATE USER 'BOARD_USR'@'%' IDENTIFIED BY 'BOARD_USR';
GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  ON *.* TO 'BOARD_USR'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;


CREATE TABLE `tbl_board` (
	`BNO` INT(11) NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(200) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`CONTENT` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`WRITER` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`REGDATE` TIMESTAMP NOT NULL DEFAULT '',
	`VIEWCNT` INT(11) NULL DEFAULT '0',
	`REPLYCNT` INT(11) NULL DEFAULT '0',
	PRIMARY KEY (`BNO`)
)

CREATE TABLE `tbl_reply` (
	`rno` INT(11) NOT NULL AUTO_INCREMENT,
	`upddate` TIMESTAMP NOT NULL DEFAULT '',
	`BNO` INT(11) NOT NULL DEFAULT '0',
	`CONTENT` VARCHAR(1000) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`WRITER` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`REGDATE` TIMESTAMP NOT NULL DEFAULT '',
	PRIMARY KEY (`rno`)
)